:tada: 유저는 수락된 제안으로 인해 생성된 채팅방 목록을 조회 할 수 있다.
team-nabi/nabi-market-client pull request #102
Opened 2023-11-23 17:17 UTC by doggopawer

## - 목적

관련 티켓 번호: 302,303

-

<br>

## - 주요 변경 사항

- 채팅방 카드 제작 및 리다이렉트 기능 구현
- 채팅방 리스트 제작 및 무한스크롤 기능 구현

## 기타 사항 (선택)

-

<br>

## - 스크린샷 (선택)

2023-11-23 17:18 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-24 05:53 UTC, oaoong approved these changes
👍

2023-11-24 05:53 UTC, oaoong commented on src/app/(root)/(routes)/chatrooms/components/chat-room-list/ChatRoomList.tsx
> +  data: InfiniteData<GetChatRoomListRes, unknown> | undefined
data 말고 다른 이름을 써도 좋을 것 같습니다!

2023-11-24 05:53 UTC, oaoong commented on src/app/(root)/(routes)/chatrooms/components/chat-room-list/ChatRoomList.tsx
> +      ({ data: { chatRoomList } }: GetChatRoomListRes, pageIndex) => (
중요한건 아닌데 함수 타입을 지정할 경우 인자와 반환값을 따로 적는 것 보다는 한 번에 함수 자체의 타입을 정하는게 좋다고 하더라고요!

2023-11-24 06:06 UTC, juyeon-park approved these changes

2023-11-24 06:21 UTC, doggopawer commented on src/app/(root)/(routes)/chatrooms/components/chat-room-list/ChatRoomList.tsx
> +      ({ data: { chatRoomList } }: GetChatRoomListRes, pageIndex) => (
좋은 개선 점 알려주셔서 감사합니다. 
혹시 근거가 근데 뭘까요?

2023-11-24 06:29 UTC, merged

2023-11-24 06:29 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-