:tada: 낙관적 업데이트 기능 구현, Mutation API 에러 처리 구현
team-nabi/nabi-market-client pull request #123
Opened 2023-11-27 13:59 UTC by doggopawer

## - 목적

관련 티켓 번호: 338, 340

-

<br>

## - 주요 변경 사항

- 제안 카드, 제안 수락/결정 기능에 낙관적 업데이트 기능 추가했습니다.
- 제안 수락/결정, 모두 읽음 처리 기능에 에러 발생시 toast 띄우도록 했습니다.
- 제안카드 이벤트 버블링 문제 해결했습니다.
- 모두 읽음 처리 버튼 => 데이터 없을 시, 지난 소식 탭일 시 경우 처리 했습니다.

## 기타 사항 (선택)

-

<br>

## - 스크린샷 (선택)

2023-11-27 15:52 UTC, juyeon-park commented on src/hooks/api/mutations/useMySuggestionUpdateMutation.ts
> +        title: '교환 제안을 결정하던 중 문제가 생겼습니다.',
`variant: 'destructive'` 추가하시면 문제가 발생했다는 것이 훨씬 명확하게 토스트메세지에서 보일 것 같네요 💯

2023-11-28 03:04 UTC, oaoong requested changes

2023-11-28 03:04 UTC, oaoong commented on src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-card/MySuggestionCard.tsx
> +    >
이거 말씀드리려했는데 카드 전체에 라우터가 씌워져있어 버튼 동작이 안 될 때가 있더라고요, 카드를 클릭해서 링크 이동하는 부분은 이미지로 한정 지으면 stopPropagation도 필요 없을 것 같습니다.

2023-11-28 05:28 UTC, doggopawer commented on src/hooks/api/mutations/useMySuggestionUpdateMutation.ts
> +        | undefined = queryClient.getQueryData([
누락된 부분이 있었네요 변경하겠습니다.

2023-11-28 05:31 UTC, doggopawer commented on src/hooks/api/mutations/useMySuggestionUpdateMutation.ts
> +        title: '교환 제안을 결정하던 중 문제가 생겼습니다.',
그러네요 훨씬 명확한 토스트가 생성됩니다 감사합니다.

2023-11-28 05:38 UTC, doggopawer commented on src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-card/MySuggestionCard.tsx
> +      }}
확실히 고민이 되던 부분이 었는데
이미지만 적용해도 좋을 것 같습니다. 반영하겠습니다!

2023-11-28 05:57 UTC, merged