:tada: 이미지 슬라이더 구현
team-nabi/nabi-market-client pull request #22
Opened 2023-11-01 01:48 UTC by juyeon-park

## - 목적

관련 티켓 번호: 87

- 이미지 슬라이더 구현

<br>

## - 주요 변경 사항

- 화살표 버튼을 통해 이전, 다음 슬라이드로 이동가능
- autoSlide를 true로 주면 default 3초마다 자동으로 슬라이더 이동 적용 가능
- 마지막 사진에서 다음 버튼 또는 첫번째 사진에서 이전 버튼을 눌렀을때 자연스러운 이동을 위해 이미지 배열에 trick용 이미지를 양쪽 끝에 추가하고 사용자는 보이지 않게 transition duration 없이 이동시킴.

## 기타 사항 (선택)

- 원래는 useRef를 이용해서 ref.current.style.transform 등등으로 조건이 일어났을 때 css 변경을 시키려고 했는데 transition, transform이 계속 안먹어서  useState 사용해서 style 내용을 계속 바꾸게 구현해놨습니다. 

<br>

## - 스크린샷 (선택)
![image](https://github.com/team-nabi/nabi-market-client/assets/61399141/efd90c0e-2214-4592-b8c1-1d992b5c2ca8)

2023-11-01 07:36 UTC, oaoong requested changes
테스트코드를 다시 확인해주세요.

2023-11-01 07:37 UTC, oaoong requested changes
테스트코드를 다시 확인해주세요.

2023-11-01 08:46 UTC, oaoong approved these changes
이런 슬라이더 같은게 만들기 꽤 까다로운데 깔끔하게 잘 만들어주셨네요!!

2023-11-01 08:46 UTC, oaoong commented on src/components/domain/Slider/Slider.tsx
> +    transform: `translateX(-${currentIndex}00%)`,
혹시 `currentIndex * 100`같은 연산으로 처리하는거 어떨까요??

2023-11-01 08:46 UTC, oaoong commented on src/components/domain/Slider/Slider.tsx
> +  return (
컴포넌트가 이미지, 버튼, 하단 인디케이터 세 가지로 분리되는 것 같은데
인디케이터 정도라도 따로 외부에서 빼서 만들면 조금 코드 읽기 수월해질 것 같습니다!

2023-11-01 08:46 UTC, oaoong commented on src/components/domain/Slider/Slider.tsx
> +    }
혹시 핸들러가 아니라 effect로 각 케이스를 따로 주어야 하는 이유가 있나요? (제가 제대로 이해를  못 한거 같아서) 궁금해서 남깁니다.

2023-11-01 08:46 UTC, oaoong commented on src/components/domain/Slider/Slider.tsx
물론 저희 기획 상 이미지가 있는 가정이지만, 해당 슬라이더는 그와 별개로 추상화되어야 하므로 이미지가 없을 때 기본 이미지가 있는게 좋을 것 같습니다! CLS 때문이라도 그게 좋을 것 같아요

2023-11-01 15:20 UTC, doggopawer approved these changes
주연님 어려운 이미지 슬라이더 구현 잘해주셨습니다. 감사합니다.

2023-11-01 15:20 UTC, doggopawer commented on src/components/domain/Slider/Slider.tsx
> +    if (coordinate.start > end && distance > 2) {
2라는 특정 숫자가 많이 나오는데, 코드에 대한 자세한 이해는 못했지만 매직넘버인 것 같아 상수화 하시면 좋을 것 같습니다.

2023-11-01 15:20 UTC, doggopawer commented on src/components/domain/Slider/Slider.tsx
> +      }, 400)
const SLIDE_TRANSITION_DELAY = 400; 으로 정의해줘도 좋을 것 같습니다.

2023-11-07 06:52 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-07 06:56 UTC, merged