:tada: ItemListPage 컴포넌트 UI 완성
team-nabi/nabi-market-client pull request #32
Opened 2023-11-02 08:31 UTC by doggopawer

## - 목적
관련 티켓 번호: 59
- 물건 목록을 조회하기 위한 페이지의 UI를 만들었습니다.

<br>

## - 주요 변경 사항

-

## 기타 사항 (선택)

- 현재 msw를 적용하지 않은 상태이며, msw는 무한스크롤을 적용할 때 사용하기로 했습니다.

<br>

## - 스크린샷 (선택)

2023-11-02 08:33 UTC, oaoong requested changes
테스트코드를 다시 확인해주세요.

2023-11-03 05:25 UTC, oaoong approved these changes

2023-11-03 05:25 UTC, oaoong commented on src/app/(root)/(routes)/items/components/SearchInput/SearchInput.tsx
> +        </svg>
요거는 SVG 파일로 저장하고 불러와서 사용하면 좋을 것 같습니다!

2023-11-03 05:29 UTC, juyeon-park reviewed
귣 👍 고생하셨어요

2023-11-03 05:29 UTC, juyeon-park commented on src/app/(root)/(routes)/items/components/ItemList/ItemList.tsx
> +import Image from 'next/image'
폴더명 케밥케이스로 하기로 했어요!!

2023-11-03 05:29 UTC, juyeon-park commented on src/app/(root)/(routes)/items/components/SearchInput/SearchInput.tsx
> +import React from 'react'
요것도 폴더명 케밥케이스!

2023-11-03 05:29 UTC, juyeon-park commented on src/components/domain/PageTitle/PageTitle.tsx
> +import Image from 'next/image'
따로 컴포넌트화 해주신거 너무 좋네요! 감사합니다 👍

2023-11-03 05:29 UTC, juyeon-park commented on src/lib/msw/mocks/itemHandler.ts
> +    const PAGE_SIZE = 5
PAGE_SIZE 관련해서 카드 조회할때 이 데이터를 백엔드에 보내주는거 맞는지 다시 백엔드랑 확인해보는게 좋을 것 같아요! 만약 맞다면 msw가 조금 수정되어야 할 것 같아요! 이전 PR과 똑같은 내용입니다!

2023-11-03 05:29 UTC, doggopawer commented on src/app/(root)/(routes)/items/components/SearchInput/SearchInput.tsx
> +        </svg>
현재 NABI-63(검색 로직 구현) 에서 해당 부분 고쳤습니다.

2023-11-03 05:30 UTC, doggopawer commented on src/app/(root)/(routes)/items/components/ItemList/ItemList.tsx
> +import Image from 'next/image'
넵 고치겠습니다.

2023-11-03 05:31 UTC, doggopawer commented on src/lib/msw/mocks/itemHandler.ts
> +    const PAGE_SIZE = 5
넵넵, 슬랙으로 한번 물어봐야겠습니다.

2023-11-03 05:33 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-03 05:53 UTC, merged