🎉 카드 삭제 구현 및 코드 정리
team-nabi/nabi-market-client pull request #57
Opened 2023-11-08 09:36 UTC by juyeon-park

## - 목적

관련 티켓 번호: 158, 159

- 158, 159 한꺼번에 했습니다

<br>

## - 주요 변경 사항

- fetchAPI 바뀐 내용 토대로 약간 코드 수정했습니다
- 카드 삭제 구현 완료 => 삭제 성공시 home으로 redirect되도록 일단 해놨습니다. 
- 삭제완료 or 삭제 실패시 토스트 메세지

## 기타 사항 (선택)

-

<br>

## - 스크린샷 (선택)

2023-11-08 09:37 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-08 09:57 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-09 04:24 UTC, oaoong approved these changes
👍

2023-11-09 04:24 UTC, oaoong commented on src/app/(root)/(routes)/items/[itemId]/components/description-section/Dibs.tsx
> +          src={dibsState ? Assets.activeHeartIcon : Assets.inactiveHeartIcon}
disState는 눌러진 상태를 뜻하는거군요? 살짝 다른 단어로 표현해도 좋을 것 같습니다

2023-11-09 14:06 UTC, juyeon-park commented on src/app/(root)/(routes)/items/[itemId]/components/description-section/Dibs.tsx
> +          src={dibsState ? Assets.activeHeartIcon : Assets.inactiveHeartIcon}
넵 is로 시작하는 단어로 표현하겠습니다. 찜이 됐는지 안됐는지에 대한 것이므로 isDibsActive도 괜찮겠네요!

2023-11-09 14:12 UTC, merged