:tada: 페이지 목록
team-nabi/nabi-market-client pull request #58
Opened 2023-11-08 13:28 UTC by doggopawer

## - 목적

관련 티켓 번호: 171

- 내 물건 목록 페이지를 완성했습니다.

<br>

## - 주요 변경 사항

- TradeStateTabs 구현 및 필터 값 적용
- 무한 스크롤링 적용

## 기타 사항 (선택)

- 소요시간 : 2시간

<br>

## - 스크린샷 (선택)

![스크린샷 2023-11-08 오후 10 27 19](https://github.com/team-nabi/nabi-market-client/assets/107387817/002ea88a-4bad-4cfc-9d45-c8b98aa2a058)

2023-11-08 13:37 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-09 04:41 UTC, oaoong approved these changes

2023-11-09 04:41 UTC, oaoong commented on src/app/(root)/(routes)/items/components/Item-list/ItemList.tsx
> +              <TradueStatusCard key={item._id} items={item} className="mb-6" />
Tradue 오타인가요?

2023-11-09 04:41 UTC, oaoong commented on src/types/index.ts
> +export interface Items {
Items로 변경한 이유가 있나요?

2023-11-09 04:41 UTC, oaoong commented on src/app/(root)/(routes)/my-items/components/my-item-card/MyItemCard.tsx
> +  <Link href={`/items?priceRange=${priceRange}`}>
링크는 양식에 등록해서 사용하면 될 것 같습니다

2023-11-09 04:41 UTC, oaoong commented on src/app/(root)/(routes)/my-items/components/my-item-card/MyItemCard.tsx
> +  <Link href={`/offers`}>
마찬가지입니다!

2023-11-09 04:41 UTC, oaoong commented on src/app/(root)/(routes)/my-items/components/my-item-card/MyItemCard.tsx
> +const MoveToItemListPage = ({ priceRange }: { priceRange: string }) => (
변수명이 적절치 않은 것 같아요. 동사로 읽히거나, Page 자체로 읽힐 수 있을 것 같습니다.

2023-11-09 04:41 UTC, oaoong commented on src/app/(root)/(routes)/my-items/components/my-item-card/MyItemCard.tsx
> +const renderMoveButtonsByStatus = (status: string, priceRange: string) => {
파라미터의 타입을 한정하면 좋을 것 같습니다

2023-11-09 06:01 UTC, doggopawer commented on src/app/(root)/(routes)/items/components/Item-list/ItemList.tsx
> +              <TradueStatusCard key={item._id} items={item} className="mb-6" />
엇...? 고치겠습니다!

2023-11-09 06:02 UTC, doggopawer commented on src/types/index.ts
> +export interface Items {
주연님이 작성한 ItemDetail 과 뭔가 혼동을 준다고 생각해서 items 라고 바꿨는데 차라리 ItemList라고 하는편이 좀더 가독성이 좋을것 같긴합니다..

2023-11-09 06:03 UTC, doggopawer commented on src/app/(root)/(routes)/my-items/components/my-item-card/MyItemCard.tsx
> +const MoveToItemListPage = ({ priceRange }: { priceRange: string }) => (
뒤에 명사를 붙이거나 새로 이름을 생각해야겠습니다.

2023-11-09 06:04 UTC, doggopawer commented on src/app/(root)/(routes)/my-items/components/my-item-card/MyItemCard.tsx
> +const renderMoveButtonsByStatus = (status: string, priceRange: string) => {
네 알겠습니다. 해당사항 고치고 머지 하도록 하겠습니다!

2023-11-09 07:12 UTC, oaoong commented on src/types/index.ts
> +export interface Items {
아 Item의 리스트가 아니라 아예 다른 내용인가요...? Item[]로 사용하지 않는 이유가 헷갈리네요.

2023-11-09 08:39 UTC, juyeon-park approved these changes
동현님 고생하셨습니다 👍 코딩 컨벤션을 지키시려고 노력하신 점이 느껴집니다 🙂

2023-11-09 08:39 UTC, juyeon-park commented on src/app/(root)/(routes)/my-items/components/my-item-card/MyItemCard.tsx
> +  switch (status) {
거래상태별로 이렇게 분기처리를 해주셨군요! 👍 다만 사용자 관점에서 버튼 유무나 종류가 다른 이유를 좀 더 쉽게 파악할 수 있기 위해 카드에 거래상태 Badge를 추가하는게 좋을 것 같은데 어떻게 생각하시나요?

2023-11-09 08:39 UTC, juyeon-park commented on src/services/my-item/myItem.ts
> +  return response.json()
최근 develop의 fetchAPI.tsx를 보면 그곳에서 response.json()형태로 내려주기 때문에 여기서 따로 json()을 안하셔도 될 것 같아요!

2023-11-09 09:04 UTC, doggopawer commented on src/types/index.ts
> +export interface Items {
일단 Item을 받아오는 6번 API와 ItemList를 받는 4번 API의 아이템들이 가진 속성들이 다릅니다.
그리고 주연님이랑 각각 개발을 진행하다보니 각각 만들었구요

2023-11-09 09:05 UTC, doggopawer commented on src/app/(root)/(routes)/my-items/components/my-item-card/MyItemCard.tsx
> +  switch (status) {
좋은 의견 감사합니다. figma 명세 대로 할 필요가 딱히 없었네요...?

2023-11-10 11:44 UTC, oaoong commented on src/types/index.ts
> +export interface Items {
혹 연관된 속성이라면 스프린트 종료되고 정리하는 시간이 있으면 좋겠네요!

2023-11-12 08:46 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-12 09:02 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-12 13:19 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-12 13:29 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-12 13:33 UTC, merged