:tada: 제안 확인 목록 페이지 완성
team-nabi/nabi-market-client pull request #61
Opened 2023-11-09 09:09 UTC by doggopawer

## - 목적

관련 티켓 번호: 172~177

<br>

## - 주요 변경 사항

- 제안 확인 목록 페이지를 만들기 위한 카드 컴포넌트를 만들었습니다.
- 제안 확인 목록 가짜 데이터, API를 만들었습니다.
- 낙관적 업데이트를 통해 오퍼 수락, 거절 버튼을 누를시 상태가 즉시 변경되도록 하였습니다.
- 제안 상태에 따른 탭을 만들었습니다.
- 제안 확인 목록 페이지를 완성했습니다.

## 기타 사항 (선택)

- 소요 시간:  172,175: 3시간 176: 30분, 174: 3시간, 177: 2시간
- 이슈 사항: 173(서버컴포넌트 데이터 받지 못하는 이슈) => 현재 서버 컴포넌트에서 데이터를 받아 하위에 컴포넌트에 넘겨줄때, 하위 컴포넌트가 데이터를 받지 못하는 이슈가 있습니다. 따라서 해당 이슈에 대해 merge하면서 조언을 얻고자 합니다.
 

<br>

## - 스크린샷 (선택)

2023-11-09 09:10 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-09 09:24 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-10 06:15 UTC, juyeon-park approved these changes
고생하셨습니다! 따봉 👍

2023-11-10 06:15 UTC, juyeon-park commented on src/app/(root)/(routes)/suggests/components/suggest-check-card/SuggestCheckCard.tsx
> +const reder = (
오타인 것 같아요! 🙂 render인건가요?

2023-11-10 06:15 UTC, juyeon-park commented on src/app/(root)/(routes)/suggests/page.tsx
경로를 mypage안에 있는 suggest느낌으로 가는건 어떨까요? 마이페이지 안에 있는 페이지라서 조금 고민이 되네요 🙂

2023-11-10 06:15 UTC, juyeon-park commented on src/app/(root)/(routes)/suggests/components/suggest-check-card/SuggestCheckCard.tsx
> +    <CardFlex className="cursor-pointer" align={'center'} gap={'space'}>
수락, 거절을 Card 컴포넌트를 사용해서 구현하신 이유가 있으신가요? 🤔 카드의 형식을 가진 컴포넌트 아니여서 div를 이용해서 해도 충분할 것 같아서요! 🙂

2023-11-11 05:57 UTC, doggopawer commented on src/app/(root)/(routes)/suggests/page.tsx
맞습니다. 그게 맞겠네요

2023-11-12 13:39 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-12 13:43 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-12 14:10 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-12 14:19 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-12 14:22 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-13 05:50 UTC, merged