🎉 이미지 슬라이더 구현 - 상세정보페이지, 홈 배너에 적용
team-nabi/nabi-market-client pull request #64
Opened 2023-11-09 13:47 UTC by juyeon-park

## - 목적

관련 티켓 번호: 155

- swiper 라이브러리 이용해서 이미지 슬라이더 변경했습니다
- 메인페이지의 배너영역과 물건상세정보페이지의 이미지 영역이 같은 디자인의 슬라이더를 사용해서 두 영역 모두 구현했습니다!
- 뭔가 bullet 보라색 색상이 어색한 것 같아서 무난한 회색으로 바꿀지 고민중입니다. 

<br>

## - 주요 변경 사항

- 

## 기타 사항 (선택)
- css에 삽질을 많이해서 시간이 많이 소요된 것 같네요 🥲 다른 작업들도 주말안에는 완료하도록 하겠습니다!
- swiper 관련해서 개발 일지는 wiki에 적었습니다
 [Carousel 라이브러리 - Swiper](https://github.com/team-nabi/nabi-market-client/wiki/Carousel-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-%E2%80%90-Swiper-%ED%99%9C%EC%9A%A9-%EB%B0%A9%EB%B2%95)

<br>

## - 스크린샷 (선택)
![image](https://github.com/team-nabi/nabi-market-client/assets/61399141/3c2f990b-621b-414a-b935-4cfa0ca5ea48)
![image](https://github.com/team-nabi/nabi-market-client/assets/61399141/844301db-b308-4899-91de-f2a00fe1d402)

2023-11-10 11:55 UTC, oaoong approved these changes
👍

2023-11-10 11:55 UTC, oaoong commented on src/app/(root)/(routes)/(home)/page.tsx
> +  ]
별건 아닌데 bannerArr가 컴포넌트 안에 있을 필요는 없을 것 같습니다. 아니면 section을 만들어서 HomeSlider로 컴포넌트 만들고 불러와줘도 좋을 것 같아요

2023-11-11 14:55 UTC, juyeon-park commented on src/app/(root)/(routes)/(home)/page.tsx
> +  ]
오 좋은 의견입니다! 따로 컴포넌트로 빼는게 좋겠네요 👍

2023-11-11 14:57 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-11 15:06 UTC, merged