🎉 거래 제안 로직 구현
team-nabi/nabi-market-client pull request #67
Opened 2023-11-11 10:01 UTC by juyeon-park

## - 목적

관련 티켓 번호: 163

-

<br>

## - 주요 변경 사항

- useQuery, useMutation이용해서 데이터를 가져오도록 변경했습니다
- 현재 useMutation의 낙관적업데이트 부분이 제대로 작동은 하는데 UI상의 변화(제안됨으로 바뀌는 변화)는 없는 버그가 있어서 해결하는 중입니다. -> 계속 안되면 이슈로 쓰겠습니다!
- onMutate를 사용해서 api 요청이 실패했을 경우 이전의 캐시를 가져와서 롤백하도록 구현했습니다.

## 기타 사항 (선택)

-

<br>

## - 스크린샷 (선택)

2023-11-12 14:51 UTC, doggopawer approved these changes
주연님, 코드 작성하시느라 고생하셨습니다!

2023-11-12 14:51 UTC, doggopawer commented on src/app/(root)/(routes)/items/[itemId]/components/trade-section/SuggestList.tsx
> +      {['OFFER', 'POKE'].map((type) => (
단 두개의 값을 렌더링 하고 있는데
두개 정도면 그냥 풀어서 써도 되지 않을까요? 이유가 궁금합니다!

2023-11-12 14:51 UTC, doggopawer commented on src/app/(root)/(routes)/items/[itemId]/components/trade-section/TradeSection.tsx
> +  const { data: suggestions } = useSuggestionsQuery(itemId)
mutation의 경우 useSuggestMutation 이라고 하셨고, query는 useSuggestionQuery로 작성하셨는데
하나로 통일이 필요할 것 같습니다!  저 같은 경우 Suggest로 통일 했습니다.

2023-11-12 14:51 UTC, doggopawer commented on src/hooks/api/mutations/useSuggestMutation.ts
> +const useSuggestMutation = (toCardId: number, fromCardId: number) => {
useSuggestMutation 같은 경우 기존 상태를 업데이트 하는것으로 보이는데
함수명을 useSuggestUpdateMutation으로 하는게 더 좋을 것 같습니다!

2023-11-12 14:51 UTC, doggopawer commented on src/hooks/api/mutations/useSuggestMutation.ts
> +      return { previousSuggestions }
혹시 UI가 바뀌지 않는 이슈가 해결되셨나요?

2023-11-13 06:07 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-13 06:08 UTC, merged

2023-11-21 05:33 UTC, juyeon-park commented on src/hooks/api/mutations/useSuggestMutation.ts
> +      return { previousSuggestions }
넵!! 해결되었습니다. 원본 데이터를 깊은 복사하여 해결하였습니다.

2023-11-21 05:38 UTC, juyeon-park commented on src/app/(root)/(routes)/items/[itemId]/components/trade-section/SuggestList.tsx
> +      {['OFFER', 'POKE'].map((type) => (
Tab Content의 내용이 많아서 풀어서 쓰지 않고 map으로 묶었습니다!

2023-11-21 05:38 UTC, juyeon-park commented on src/app/(root)/(routes)/items/[itemId]/components/trade-section/TradeSection.tsx
> +  const { data: suggestions } = useSuggestionsQuery(itemId)
오 좋은 의견 감사합니다! suggestion으로 통일시키겠습니다!