:tada: 찜 페이지 목록 구현
team-nabi/nabi-market-client pull request #68
Opened 2023-11-11 12:37 UTC by juyeon-park

## - 목적

관련 티켓 번호: 160, 161

- mock api와 페이지 연결을 한꺼번에 했습니다!

<br>

## - 주요 변경 사항

- 동현님이 작성하신 무한스크롤 코드를 토대로 구현했습니다!
- route 경로를 mypage안에 있는 mydibs로 할지 별개로 mydibs로 둘지 고민이 되네요

## 기타 사항 (선택)

-

<br>

## - 스크린샷 (선택)
![image](https://github.com/team-nabi/nabi-market-client/assets/61399141/3f73c17e-1a7f-47d2-a67f-95f96bb8e814)

2023-11-12 14:57 UTC, doggopawer approved these changes
주연님 코드 작성하시느라 수고 하셨습니다!

2023-11-12 14:57 UTC, doggopawer commented on src/app/(root)/(routes)/mydibs/my-dibs-list/MyDibsList.tsx
> +                className="mb-6 w-[80%]"
재희님께서 이부분이 다소 이해하기 난해할수 있다 하셔서,
저같은 경우는 상수화 처리를 아래와 같이 했습니다.

```
const hasData = data?.pages[0].length !== 0
const pages = data?.pages

{hasData
          ? pages?.map((currentPage, pageIndex) => (
              <Fragment key={pageIndex}>
                {currentPage.map((item: Item) => (
                  <TradeStatusCard
                    key={item.cardId}
                    item={item}
                    className="mb-6"
                  />
                ))}
              </Fragment>
            ))
          : '데이터가 없습니다.'}
```
리스트 페이지가 비슷한 구조여서, 코드도 비슷하면 좋을것 같은 취지에서 코드 올려드렸습니다!

2023-11-12 14:57 UTC, doggopawer commented on src/lib/msw/mocks/data/items.json
> +    "thumbNail": "https://cdn.cetizen.com/CDN/market/market_large_crop/202203/20220318/220318152808_1_2913635.jpg",
혹시 이거 제가 작성한 items.json 목데이터 맞나요?
이게 thumbNail로 바뀌어서 제 코드가 제대로 작동할지 의문입니다
혹은 충돌이 날것 같아요

2023-11-13 05:16 UTC, juyeon-park commented on src/lib/msw/mocks/data/items.json
> +    "thumbNail": "https://cdn.cetizen.com/CDN/market/market_large_crop/202203/20220318/220318152808_1_2913635.jpg",
넵 동현님이 작성하신 items.json이 맞습니다! api 명세서들이 업데이트 되면서 tradestate 카드를 재사용하려면 변수명을 다 맞춰야되서 api 명세서대로 thumbNail로 바꿨습니다!

2023-11-13 05:54 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-13 06:01 UTC, merged