🎉 오늘의 인기물건 api 연결
team-nabi/nabi-market-client pull request #88
Opened 2023-11-20 07:43 UTC by juyeon-park

## - 목적

관련 티켓 번호: 260

-

<br>

## - 주요 변경 사항

- 오늘의 인기물건 api 연결 완료
- 현재 백엔드에서 DB에 임시로 만들어놓은  dummyData의 이미지 url이 dummyimage.com으로 이루어져 있어서 임시로 next.config에 추가해놨습니다.

## 기타 사항 (선택)

-

<br>

## - 스크린샷 (선택)
![image](https://github.com/team-nabi/nabi-market-client/assets/61399141/848be8aa-8347-4af2-b1bf-b62bfa1ff877)

2023-11-20 07:44 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-20 19:36 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-20 19:41 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-21 05:37 UTC, doggopawer approved these changes

2023-11-21 05:37 UTC, doggopawer commented on next.config.js
> +      },
저도 이부분을 추가하긴 했었는데, 이런식으로 디테일하게 설정하지 않아서 나중에 삭제하든지 해야겠습니다.

2023-11-21 06:02 UTC, juyeon-park commented on next.config.js
> +      },
그쵸! FIXME-삭제예정으로 주석 달아놓겠습니다!

2023-11-21 07:34 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-21 07:41 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-21 08:04 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-21 08:05 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-21 08:52 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-21 13:49 UTC, oaoong approved these changes

2023-11-21 13:49 UTC, oaoong commented on src/services/card/card.ts
> +    { next: { revalidate: 60 } },
revalidate 엄청 잦네요 혹시 매번 하는 것과 유의미한 차이가 있어서 설정된 수치인가요?

2023-11-22 04:14 UTC, juyeon-park commented on src/services/card/card.ts
> +    { next: { revalidate: 60 } },
처음에는 100분이 적절한 것 같아서 6000으로 설정했는데 조회수로 인해 데이터가 변화 빈도수가 많아서 1분으로 설정했던 것 같네요. 하지만 1분은 트래픽을 많이 잡아먹을 수도 있을 것 같습니다. 1시간 정도로 변경하려는데 어떠신가요?

2023-11-22 04:19 UTC, oaoong commented on src/services/card/card.ts
> +    { next: { revalidate: 60 } },
아아 이거 초 단위죠? 그러면 괜찮을거같아요 제가 오해했어요ㅋㅋㅋ

2023-11-22 04:27 UTC, juyeon-park commented on src/services/card/card.ts
> +    { next: { revalidate: 60 } },
앗 그럼 1분으로 진행하고 문제 생기면 좀 더 늘리는 방향으로 하겠습니다!

2023-11-22 04:33 UTC, merged