:tada: 각 리스트 조회 페이지 API 연결, 코드 리팩토링
team-nabi/nabi-market-client pull request #89
Opened 2023-11-20 13:33 UTC by doggopawer

## - 목적

관련 티켓 번호: 248, 249

- 각 리스트 조회 페이지 API 연결 및 코드 리팩토링 했습니다.

<br>

## - 주요 변경 사항

- CategoryObjs, PriceObjs 등으로 타입 변경했습니다.
- 각 API  목록 조회 페이지에 연결했습니다.
- 각 API 응답 타입 새로 정의했습니다. (GetMyCardListRes, Req 등)
- 각 ListContent 컴포넌트와, List 컴포넌트를 분리했습니다.
- MySuggestion 페이지 slug 적용했습니다.
- 제안수락, 거절 낙관적 업데이트 및 API 기능 보류 했습니다.(pageInfo를 res 데이터에 클라이언트에서 추가하는 방식 보다 더 좋은 방법을 생각해보겠습니다.)
## 기타 사항 (선택)

-

<br>

## - 스크린샷 (선택)

2023-11-20 13:42 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-21 05:35 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-21 05:48 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-21 06:01 UTC, juyeon-park approved these changes
👍

2023-11-21 06:29 UTC, doggopawer commented on src/services/suggestion/suggestion.ts
> +  cardId: string | string[]
useParams로 path-variable  의 값을 불러올시, 위 타입을 충족하라고 해서 저렇게 했습니다!

2023-11-21 06:30 UTC, doggopawer commented on src/hooks/api/queries/useCardsQuery.ts
> +    queryFn: async ({ pageParam = undefined }) =>
기존의 무한 스크롤 paging 방식이 offset (1부터 증가) 하는 방식이 아니라
백엔드에서 nextCursorId라는 값을 주기 때문에, pageParam을 undefined로 줄 필요가 있었습니다.

2023-11-21 06:31 UTC, doggopawer commented on src/app/(root)/(routes)/mypage/suggestions/[cardId]/components/my-suggestion-list-content/MySuggestionListContent.tsx
> +  const isEmpty = data?.pages[0].data.suggestionList.length === 0
참고해서 가능하면 반영하겠습니다!

2023-11-21 07:51 UTC, merged