:tada: 유저는 제안 요청, 제안 수락/거절, 거래 성사 요청에 대한 알림을 조회 할 수 있다.
team-nabi/nabi-market-client pull request #97
Opened 2023-11-22 11:01 UTC by doggopawer

## - 목적

관련 티켓 번호: 282,283,284,285,289

- 알림 페이지를 완성 했습니다.

<br>

## - 주요 변경 사항

- 알림 카드 제작 및 페이지 이동 기능 구현
-  알림 리스트 제작 및 알림 조회 기능 구현
-  알림 탭 제작 및 알림 종류별 조회 기능 구현
-  읽음 처리 버튼 제작 및 읽음 처리 기능 구현
- 알림 페이지 제작 및 컴포넌트 연결 구현

## 기타 사항 (선택)

- 총 소요시간(4시간)

<br>

## - 스크린샷 (선택)
![스크린샷 2023-11-22 오후 8 00 33](https://github.com/team-nabi/nabi-market-client/assets/107387817/c9081a9e-f50f-4b62-9183-04463d35a83b)
![스크린샷 2023-11-22 오후 8 00 29](https://github.com/team-nabi/nabi-market-client/assets/107387817/d06e2d35-569c-4199-8912-523d50778c18)

2023-11-22 11:02 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-22 17:14 UTC, juyeon-park approved these changes
고생하셨습니다 👋

2023-11-22 17:14 UTC, juyeon-park commented on src/app/(root)/(routes)/mypage/notifications/components/notification-status-tabs/NotificationStatusTabs.tsx
> +    <Tabs
앗 혹시 탭의 width 크기를 화면 꽉차게 하기로 한 의견은 혹시 철회된건가요? 🤔 제안하신 의견이 디자인에 더 좋았어서 여쭤봅니다

2023-11-22 17:14 UTC, juyeon-park commented on src/hooks/api/mutations/useNotificationListUpdateMutation.ts
> +      // TODO : 에러처리 및 각 종 Optimistic Update 관련 기능 처리하기
카드를 누르는 순간 무조건 다른 페이지로 이동하게 되서 따로 낙관적 업데이트가 실질적으로 필요할지 궁금합니다 🤔

2023-11-22 17:14 UTC, juyeon-park commented on src/hooks/api/mutations/useNotificationListUpdateMutation.ts
> +    onSettled: () => {
onSettled는 한번도 안써봤는데 어떤 기능인가요?

2023-11-22 17:14 UTC, juyeon-park commented on src/app/(root)/(routes)/mypage/notifications/components/notification-card/NotificationCard.tsx
> +              <CardImage
벨 아이콘으로 모두 통일 굳~ 👍

2023-11-23 04:49 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-23 04:49 UTC, doggopawer commented on src/app/(root)/(routes)/mypage/notifications/components/notification-status-tabs/NotificationStatusTabs.tsx
> +    <Tabs
그거 Tabs 내부에서 하는게 아니라 외부에서 css를 줘야하는건가요? 몰랐습니다.

2023-11-23 04:50 UTC, doggopawer commented on src/hooks/api/mutations/useNotificationListUpdateMutation.ts
> +      // TODO : 에러처리 및 각 종 Optimistic Update 관련 기능 처리하기
알림페이지의 모두 읽음 처리를 눌렀을 때 라서 페이지 이동은 없습니다!
사실 아직 네트워크가 느리지 않아서 낙관적 업데이트가 저도 필요한지는 잘 모르겠습니다.

2023-11-23 04:51 UTC, doggopawer commented on src/hooks/api/mutations/useNotificationListUpdateMutation.ts
> +    onSettled: () => {
onError, onSuccess처럼 성공, 실패 여부에 따라 동작하는게 아니라
항상 동작하는 핸들러입니다!

2023-11-23 04:53 UTC, oaoong requested changes
actions 결과를 다시 확인해주세요. -자동으로 작성됨-

2023-11-23 06:45 UTC, merged